### ISSUE TITLE
QA_Pattern Recognition_Feedback_p1

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/pattern-recognition-iiith#1]
Defect Description :
In Home page of "Pattern Recognition "Lab,  when we click on the link Feedback , it is redirecting to an error page (404) instead it should redirect to a new page with the selected link 

Actual Result :
In Home page of "Pattern Recognition "Lab, when we click on the link Feedback , it is redirecting to an error page (404)

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/pattern-recognition-iiith/blob/master/test-cases/integration_test-cases/System/Pattern%20Recognition_08_Feedback_p1.org

Attachment: 
![pr10](https://cloud.githubusercontent.com/assets/14869397/14601152/1d49b0d2-057e-11e6-808a-044d01b28aca.png)

**Comment by sravanthimodepu** [comment]
Issue is fixed now.

**Comment by BSravanthi** [comment]
Closed the issue.
