### ISSUE TITLE
QA_Generation of Random Variables_Back to experiments_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/pattern-recognition-iiith#10]
Defect Description :
In " Generation of Random Variables  " experiment, the back to experiments link is not present instead back to experiments link should be there in-order to view the list of experiments by the end user

Actual Result :
In " Generation of Random Variables  " experiment, the back to experiments link is not present in the page

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/pattern-recognition-iiith/blob/master/test-cases/integration_test-cases/Generation%20of%20Random%20Variables/Generation%20of%20Random%20Variables_13_Back%20to%20experiments_smk.org

Attachment: 
![pr6](https://cloud.githubusercontent.com/assets/14869397/14601387/79340efa-057f-11e6-81a5-d359cc31ec0d.png)

**Comment by sravanthimodepu** [comment]
Issue is fixed now.

**Comment by BSravanthi** [comment]
Closing the issue.
