### ISSUE TITLE
QA_Linear Perceptron Learning_Back to experiments_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/pattern-recognition-iiith#12]
Defect Description :
In "Linear Perceptron Learning " experiment, the back to experiments link is not present instead back to experiments link should be there in-order to view the list of experiments by the end user 

Actual Result :
In "Linear Perceptron Learning " experiment, the back to experiments link is not present in the page)

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/pattern-recognition-iiith/blob/master/test-cases/integration_test-cases/Linear%20Perceptron%20Learning/Linear%20Perceptron%20Learning_13_Back%20to%20experiments_smk.org

Attachment: 
![pr5](https://cloud.githubusercontent.com/assets/14869397/14601354/452b0992-057f-11e6-8920-4dc276fd5f06.png)

**Comment by sravanthimodepu** [comment]
Issue is fixed now.

**Comment by BSravanthi** [comment]
Issue is closed.
