### ISSUE TITLE
QA_Linear Perceptron Learning_Further Readings_p2

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/pattern-recognition-iiith#13]
Defect Description :
In Further Readings page of "Linear Perceptron Learning " experiment,  when we click on the link Perceptron Learning Applet at CMU , it is redirecting to an error page (404) instead it should redirect to a new page with the selected link 

Actual Result :
In Further Readings page of "Linear Perceptron Learning " experiment, when we click on the link Perceptron Learning Applet at CMU , it is redirecting to an error page (404)

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/pattern-recognition-iiith/blob/master/test-cases/integration_test-cases/Linear%20Perceptron%20Learning/Linear%20Perceptron%20Learning_12_Further%20Readings_p1.org

Attachment: 
![pr4](https://cloud.githubusercontent.com/assets/14869397/14601332/2cc417fe-057f-11e6-8117-7d16fe560845.png)

**Comment by BSravanthi** [comment]
Issue is already raised. Can refer to issue number #14. Hence closing this issue.
