### ISSUE TITLE
QA_Mean and Covariance_Back to experiments_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/pattern-recognition-iiith#16]
Defect Description :
In "Mean and Covariance " experiment, the back to experiments link is not present instead back to experiments link should be there in-order to view the list of experiments by the end user

Actual Result :
In "Mean and Covariance " experiment, the back to experiments link is not present in the page

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/pattern-recognition-iiith/blob/master/test-cases/integration_test-cases/Mean%20and%20Covariance/Mean%20and%20Covariance_13_Back%20to%20expe_smkriments.org

Attachment: 
![pr2](https://cloud.githubusercontent.com/assets/14869397/14601257/df1327e8-057e-11e6-9388-85435e182ced.png)

**Comment by sravanthimodepu** [comment]
Issue is fixed now.

**Comment by BSravanthi** [comment]
Issue is closed.
