### ISSUE TITLE
QA_Feature Representation_Back to experiments_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/pattern-recognition-iiith#18]
Defect Description :
In "Feature Representation " experiment, the back to experiments link is not present instead back to experiments link should be there in-order to view the list of experiments by the end user

Actual Result :
In "Feature Representation " experiment, the back to experiments link is not present in the page

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/pattern-recognition-iiith/blob/master/test-cases/integration_test-cases/Feature%20Representation/Feature%20Representation_13_Back%20to%20experiments_smk.org

Attachment: 
![pr1](https://cloud.githubusercontent.com/assets/14869397/14601162/2ef749e8-057e-11e6-9988-0b3e7835d93d.png)

**Comment by sravanthimodepu** [comment]
issue is fixed now.

**Comment by BSravanthi** [comment]
Issue is closed.
