### ISSUE TITLE
Need to add Further Readings Page

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/pattern-recognition-iiith#20]
@sravanthimodepu In the Experiment page of Mean and Covariance Experiment Further Readings Page needs to be included where are in all the pages of all experiments of this lab includes Further Readings Page

**Comment by sravanthimodepu** [comment]
Issue is fixed now.

**Comment by BSravanthi** [comment]
Issue yet to be fixed

**Comment by sravanthimodepu** [comment]
All the links are updated in the further readings page. Issue is fixed now.

**Comment by BSravanthi** [comment]
Closed #20
