### ISSUE TITLE
Include "Evaluate" and "Reset" buttons in Quizzes page

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/pattern-recognition-iiith#21]
In the Quizzes page of Mean and Covariance experiment of this lab, the answers may have radio buttons option followed by "Evaluate" and "Reset" buttons in order to take the quiz and gets evaluated for the user's convenience.

**Comment by sravanthimodepu** [comment]
Radio buttons, Evaluate and Reset buttons are updated in the quiz section. Issue is fixed now.

**Comment by BSravanthi** [comment]
Closed #21
