### ISSUE TITLE
Further Readings page redirecting to an Error page.

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/pattern-recognition-iiith#23]
@sravanthimodepu In the **Generating Random Numbers** Experiment of **Pattern Recognition** Lab, When we select Further Readings link from Procedure link the page is redirecting to an Error page showing "Page not found" message, where as when we click on Further Readings link from Procedure link it should redirect to Further Readings page.

**Comment by sravanthimodepu** [comment]
Issue is fixed now.

**Comment by BSravanthi** [comment]
Closed #23
