### ISSUE TITLE
Inappropriate links in  MLE: Learning the classifier from data 

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/pattern-recognition-iiith#26]
In the Further Readings page of  **MLE: Learning the classifier from data**  experiment in the **Pattern Recognition** lab, both Bayes Theorem and Naive Bayes Classifier links are related to  Bayesian Classification  Experiment in the same lab.

**Comment by sravanthimodepu** [comment]
Links are related to the experiment itself, so differing this issue .

**Comment by BSravanthi** [comment]
Closed #26
