### ISSUE TITLE
Junk Characters and inconsistency in Quizzes page of  Data Clustering: K-Means, MST-based 

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/pattern-recognition-iiith#27]
In the Quizzes page of  Data Clustering: K-Means, MST-based in Pattern Recognition Lab, Junk characters are present in Quizzes section and Inconsistency of the data needs to be corrected.

**Comment by sravanthimodepu** [comment]
Issue is fixed now.

**Comment by BSravanthi** [comment]
Closed #27
