### ISSUE TITLE
List of Experiments Link directing to inappropriate page.

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/pattern-recognition-iiith#28]
From the Feedback page of Feature Representation experiment of Pattern Recognition Lab, when we select **List of experiments** link, the link is directing to the main page of the lab, where as the link should direct to the page where lost of experiments are present.

**Comment by sravanthimodepu** [comment]
"List of experiments" link is updated in the Further Readings page. Issue is fixed now.

**Comment by BSravanthi** [comment]
Closed #28
