### ISSUE TITLE
Name of the Lab is differed in all the pages

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/pattern-recognition-iiith#29]
The name of the lab is differed in all the pages of the lab. The lab name should be given as Pattern Recognition Lab, instead of PR Virtual lab.

**Comment by sravanthimodepu** [comment]
Name of the lab is changed from PR Virtual Lab to Pattern Recognition Lab. Issue is fixed now.

**Comment by BSravanthi** [comment]
Closed #29
