### ISSUE TITLE
QA_Data Clustering: K-Means, MST-based_Back to experiments_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/pattern-recognition-iiith#3]
Defect Description :
In "Data Clustering: K-Means, MST-based  " experiment, the back to experiments link is not present instead back to experiments link should be there in-order to view the list of experiments by the end user

Actual Result :
In "Data Clustering: K-Means, MST-based  " experiment, the back to experiments link is not present in the page

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/pattern-recognition-iiith/blob/master/test-cases/integration_test-cases/Data%20Clustering%20K-Means%2C%20MST-ba/Data%20Clustering%20K-Means%2C%20MST-ba_13_Back%20to%20experiments_smk.org

Attachment: 
![pr9](https://cloud.githubusercontent.com/assets/14869397/14601559/5b93469e-0580-11e6-9204-20913f456557.png)

**Comment by sravanthimodepu** [comment]
Issue is fixed now.

**Comment by BSravanthi** [comment]
Closed the issue.
