### ISSUE TITLE
Name of the experiment needs to be changed

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/pattern-recognition-iiith#31]
Name of the experiment needs to be changed in all the pages of  **Generation of Random Variables**. The name in all the 8 pages of the experiment is given as **Generating Random Numbers**

**Comment by sravanthimodepu** [comment]
Name of the experiment is changed accordingly. Issue is fixed now.

**Comment by BSravanthi** [comment]
Closed #31
