### ISSUE TITLE
QA_MLE: Learning the classifier from data_Back to experiments_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/pattern-recognition-iiith#5]
Defect Description :
In "MLE: Learning the classifier from data  " experiment, the back to experiments link is not present instead back to experiments link should be there in-order to view the list of experiments by the end user

Actual Result :
In "MLE: Learning the classifier from data  " experiment, the back to experiments link is not present in the page

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/pattern-recognition-iiith/blob/master/test-cases/integration_test-cases/MLE%20Learning%20the%20classifier%20fro/MLE%20Learning%20the%20classifier%20fro_13_Back%20to%20experiments_smk.org

Attachment: 
![pr8](https://cloud.githubusercontent.com/assets/14869397/14601542/375423de-0580-11e6-9165-67b852126769.png)

**Comment by sravanthimodepu** [comment]
issue is fixed now.

**Comment by BSravanthi** [comment]
Issue is closed.
